//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXTF.Lib.AdminModel.Model
{
    using System;

    public partial class Holiday
    {
        public long SL { get; set; }
        public Nullable<System.DateTime> HolidayStartDate { get; set; }
        public Nullable<System.DateTime> HolidayEndDate { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
    }
}
